site_name: PyPathway
theme: 'material'
pages: 
- Get Started: 'index.md'
- User Guide:
    - 'Writing your docs': 'user-guide/docs.md'
    - 'Styling your docs': 'user-guide/docs.md'
repo_name: 'GitHub'
repo_url: 'https://github.com/iseekwonderful/csgoGlow'
extra:
  version: '0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'white'
    accent: 'orange'
  author:
    github: 'iseekwonderful'
markdown_extensions:
  - admonition
  - codehilite(css_class=code)
extra_css: ['stylesheets/extra.css']